package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationRepositorySetting;
import com.fit2cloud.devops.base.domain.ApplicationRepositorySettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationRepositorySettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    long countByExample(ApplicationRepositorySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationRepositorySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int insert(ApplicationRepositorySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationRepositorySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    List<ApplicationRepositorySetting> selectByExample(ApplicationRepositorySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    ApplicationRepositorySetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationRepositorySetting record, @Param("example") ApplicationRepositorySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationRepositorySetting record, @Param("example") ApplicationRepositorySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationRepositorySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationRepositorySetting record);
}