package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationDeploymentLog;
import com.fit2cloud.devops.base.domain.ApplicationDeploymentLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationDeploymentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    long countByExample(ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int insert(ApplicationDeploymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationDeploymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    List<ApplicationDeploymentLog> selectByExampleWithBLOBs(ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    List<ApplicationDeploymentLog> selectByExample(ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    ApplicationDeploymentLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationDeploymentLog record, @Param("example") ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationDeploymentLog record, @Param("example") ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationDeploymentLog record, @Param("example") ApplicationDeploymentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationDeploymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationDeploymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationDeploymentLog record);
}