package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationSetting;
import com.fit2cloud.devops.base.domain.ApplicationSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    long countByExample(ApplicationSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int insert(ApplicationSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    List<ApplicationSetting> selectByExample(ApplicationSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    ApplicationSetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationSetting record, @Param("example") ApplicationSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationSetting record, @Param("example") ApplicationSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationSetting record);
}