package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationRepository;
import com.fit2cloud.devops.base.domain.ApplicationRepositoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationRepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    long countByExample(ApplicationRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int insert(ApplicationRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    List<ApplicationRepository> selectByExample(ApplicationRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    ApplicationRepository selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationRepository record, @Param("example") ApplicationRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationRepository record, @Param("example") ApplicationRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationRepository record);
}