package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationVersion;
import com.fit2cloud.devops.base.domain.ApplicationVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    long countByExample(ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int insert(ApplicationVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    List<ApplicationVersion> selectByExampleWithBLOBs(ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    List<ApplicationVersion> selectByExample(ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    ApplicationVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationVersion record, @Param("example") ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationVersion record, @Param("example") ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationVersion record, @Param("example") ApplicationVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationVersion record);
}