package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationDeploySettings;
import com.fit2cloud.devops.base.domain.ApplicationDeploySettingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationDeploySettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    long countByExample(ApplicationDeploySettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationDeploySettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int insert(ApplicationDeploySettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationDeploySettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    List<ApplicationDeploySettings> selectByExample(ApplicationDeploySettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    ApplicationDeploySettings selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationDeploySettings record, @Param("example") ApplicationDeploySettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationDeploySettings record, @Param("example") ApplicationDeploySettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationDeploySettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deploy_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationDeploySettings record);
}