package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ApplicationDeploymentEventLog;
import com.fit2cloud.devops.base.domain.ApplicationDeploymentEventLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationDeploymentEventLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    long countByExample(ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int insert(ApplicationDeploymentEventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int insertSelective(ApplicationDeploymentEventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    List<ApplicationDeploymentEventLog> selectByExampleWithBLOBs(ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    List<ApplicationDeploymentEventLog> selectByExample(ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    ApplicationDeploymentEventLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplicationDeploymentEventLog record, @Param("example") ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationDeploymentEventLog record, @Param("example") ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplicationDeploymentEventLog record, @Param("example") ApplicationDeploymentEventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApplicationDeploymentEventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationDeploymentEventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApplicationDeploymentEventLog record);
}