package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.CloudServerDevops;
import com.fit2cloud.devops.base.domain.CloudServerDevopsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudServerDevopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    long countByExample(CloudServerDevopsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int deleteByExample(CloudServerDevopsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int insert(CloudServerDevops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int insertSelective(CloudServerDevops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    List<CloudServerDevops> selectByExample(CloudServerDevopsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    CloudServerDevops selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudServerDevops record, @Param("example") CloudServerDevopsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudServerDevops record, @Param("example") CloudServerDevopsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudServerDevops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server_devops
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudServerDevops record);
}