package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.Cluster;
import com.fit2cloud.devops.base.domain.ClusterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    long countByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int deleteByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int insert(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int insertSelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    List<Cluster> selectByExample(ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    Cluster selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cluster record, @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cluster record, @Param("example") ClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cluster record);
}