package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ClusterRole;
import com.fit2cloud.devops.base.domain.ClusterRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClusterRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    long countByExample(ClusterRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int deleteByExample(ClusterRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int insert(ClusterRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int insertSelective(ClusterRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    List<ClusterRole> selectByExample(ClusterRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    ClusterRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ClusterRole record, @Param("example") ClusterRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ClusterRole record, @Param("example") ClusterRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClusterRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cluster_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClusterRole record);
}