package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsJenkinsView;
import com.fit2cloud.devops.base.domain.DevopsJenkinsViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsJenkinsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    long countByExample(DevopsJenkinsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsJenkinsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int insert(DevopsJenkinsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int insertSelective(DevopsJenkinsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    List<DevopsJenkinsView> selectByExample(DevopsJenkinsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    DevopsJenkinsView selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsJenkinsView record, @Param("example") DevopsJenkinsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsJenkinsView record, @Param("example") DevopsJenkinsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsJenkinsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsJenkinsView record);
}