package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsJenkinsParams;
import com.fit2cloud.devops.base.domain.DevopsJenkinsParamsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsJenkinsParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    long countByExample(DevopsJenkinsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsJenkinsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int insert(DevopsJenkinsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int insertSelective(DevopsJenkinsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    List<DevopsJenkinsParams> selectByExample(DevopsJenkinsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    DevopsJenkinsParams selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsJenkinsParams record, @Param("example") DevopsJenkinsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsJenkinsParams record, @Param("example") DevopsJenkinsParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsJenkinsParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsJenkinsParams record);
}