package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsJenkinsJobHistory;
import com.fit2cloud.devops.base.domain.DevopsJenkinsJobHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsJenkinsJobHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    long countByExample(DevopsJenkinsJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsJenkinsJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int insert(DevopsJenkinsJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int insertSelective(DevopsJenkinsJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    List<DevopsJenkinsJobHistory> selectByExample(DevopsJenkinsJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    DevopsJenkinsJobHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsJenkinsJobHistory record, @Param("example") DevopsJenkinsJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsJenkinsJobHistory record, @Param("example") DevopsJenkinsJobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsJenkinsJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsJenkinsJobHistory record);
}