package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsScriptFilter;
import com.fit2cloud.devops.base.domain.DevopsScriptFilterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsScriptFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    long countByExample(DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int insert(DevopsScriptFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int insertSelective(DevopsScriptFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    List<DevopsScriptFilter> selectByExampleWithBLOBs(DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    List<DevopsScriptFilter> selectByExample(DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    DevopsScriptFilter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsScriptFilter record, @Param("example") DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DevopsScriptFilter record, @Param("example") DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsScriptFilter record, @Param("example") DevopsScriptFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsScriptFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DevopsScriptFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_filter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsScriptFilter record);
}