package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsJenkinsCredential;
import com.fit2cloud.devops.base.domain.DevopsJenkinsCredentialExample;
import com.fit2cloud.devops.base.domain.DevopsJenkinsCredentialWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsJenkinsCredentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    long countByExample(DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int insert(DevopsJenkinsCredentialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int insertSelective(DevopsJenkinsCredentialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    List<DevopsJenkinsCredentialWithBLOBs> selectByExampleWithBLOBs(DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    List<DevopsJenkinsCredential> selectByExample(DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    DevopsJenkinsCredentialWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsJenkinsCredentialWithBLOBs record, @Param("example") DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DevopsJenkinsCredentialWithBLOBs record, @Param("example") DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsJenkinsCredential record, @Param("example") DevopsJenkinsCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsJenkinsCredentialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DevopsJenkinsCredentialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsJenkinsCredential record);
}