package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsCloudServer;
import com.fit2cloud.devops.base.domain.DevopsCloudServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsCloudServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    long countByExample(DevopsCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int insert(DevopsCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int insertSelective(DevopsCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    List<DevopsCloudServer> selectByExample(DevopsCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    DevopsCloudServer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsCloudServer record, @Param("example") DevopsCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsCloudServer record, @Param("example") DevopsCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsCloudServer record);
}