package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.DevopsViewJobMapping;
import com.fit2cloud.devops.base.domain.DevopsViewJobMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsViewJobMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    long countByExample(DevopsViewJobMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsViewJobMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int insert(DevopsViewJobMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int insertSelective(DevopsViewJobMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    List<DevopsViewJobMapping> selectByExample(DevopsViewJobMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    DevopsViewJobMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsViewJobMapping record, @Param("example") DevopsViewJobMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsViewJobMapping record, @Param("example") DevopsViewJobMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsViewJobMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_jenkins_view_job_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsViewJobMapping record);
}