package com.fit2cloud.devops.base.mapper;

import com.fit2cloud.devops.base.domain.ScriptImplementLog;
import com.fit2cloud.devops.base.domain.ScriptImplementLogExample;
import com.fit2cloud.devops.base.domain.ScriptImplementLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScriptImplementLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    long countByExample(ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int deleteByExample(ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int insert(ScriptImplementLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int insertSelective(ScriptImplementLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    List<ScriptImplementLogWithBLOBs> selectByExampleWithBLOBs(ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    List<ScriptImplementLog> selectByExample(ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    ScriptImplementLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ScriptImplementLogWithBLOBs record, @Param("example") ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ScriptImplementLogWithBLOBs record, @Param("example") ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ScriptImplementLog record, @Param("example") ScriptImplementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScriptImplementLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ScriptImplementLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScriptImplementLog record);
}