package com.fit2cloud.devops.base.domain;

import java.util.ArrayList;
import java.util.List;

public class ApplicationDeploymentEventLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public ApplicationDeploymentEventLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdIsNull() {
            addCriterion("deployment_log_id is null");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdIsNotNull() {
            addCriterion("deployment_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdEqualTo(String value) {
            addCriterion("deployment_log_id =", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdNotEqualTo(String value) {
            addCriterion("deployment_log_id <>", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdGreaterThan(String value) {
            addCriterion("deployment_log_id >", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdGreaterThanOrEqualTo(String value) {
            addCriterion("deployment_log_id >=", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdLessThan(String value) {
            addCriterion("deployment_log_id <", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdLessThanOrEqualTo(String value) {
            addCriterion("deployment_log_id <=", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdLike(String value) {
            addCriterion("deployment_log_id like", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdNotLike(String value) {
            addCriterion("deployment_log_id not like", value, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdIn(List<String> values) {
            addCriterion("deployment_log_id in", values, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdNotIn(List<String> values) {
            addCriterion("deployment_log_id not in", values, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdBetween(String value1, String value2) {
            addCriterion("deployment_log_id between", value1, value2, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andDeploymentLogIdNotBetween(String value1, String value2) {
            addCriterion("deployment_log_id not between", value1, value2, "deploymentLogId");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNull() {
            addCriterion("event_name is null");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNotNull() {
            addCriterion("event_name is not null");
            return (Criteria) this;
        }

        public Criteria andEventNameEqualTo(String value) {
            addCriterion("event_name =", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotEqualTo(String value) {
            addCriterion("event_name <>", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThan(String value) {
            addCriterion("event_name >", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThanOrEqualTo(String value) {
            addCriterion("event_name >=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThan(String value) {
            addCriterion("event_name <", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThanOrEqualTo(String value) {
            addCriterion("event_name <=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLike(String value) {
            addCriterion("event_name like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotLike(String value) {
            addCriterion("event_name not like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameIn(List<String> values) {
            addCriterion("event_name in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotIn(List<String> values) {
            addCriterion("event_name not in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameBetween(String value1, String value2) {
            addCriterion("event_name between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotBetween(String value1, String value2) {
            addCriterion("event_name not between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Long value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Long value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Long value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Long value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Long value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Long> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Long> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Long value1, Long value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Long value1, Long value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Long value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Long value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Long value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Long value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Long value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Long> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Long> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Long value1, Long value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Long value1, Long value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSOrderIsNull() {
            addCriterion("s_order is null");
            return (Criteria) this;
        }

        public Criteria andSOrderIsNotNull() {
            addCriterion("s_order is not null");
            return (Criteria) this;
        }

        public Criteria andSOrderEqualTo(Integer value) {
            addCriterion("s_order =", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderNotEqualTo(Integer value) {
            addCriterion("s_order <>", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderGreaterThan(Integer value) {
            addCriterion("s_order >", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_order >=", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderLessThan(Integer value) {
            addCriterion("s_order <", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderLessThanOrEqualTo(Integer value) {
            addCriterion("s_order <=", value, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderIn(List<Integer> values) {
            addCriterion("s_order in", values, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderNotIn(List<Integer> values) {
            addCriterion("s_order not in", values, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderBetween(Integer value1, Integer value2) {
            addCriterion("s_order between", value1, value2, "sOrder");
            return (Criteria) this;
        }

        public Criteria andSOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("s_order not between", value1, value2, "sOrder");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdIsNull() {
            addCriterion("application_version_id is null");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdIsNotNull() {
            addCriterion("application_version_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdEqualTo(String value) {
            addCriterion("application_version_id =", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdNotEqualTo(String value) {
            addCriterion("application_version_id <>", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdGreaterThan(String value) {
            addCriterion("application_version_id >", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("application_version_id >=", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdLessThan(String value) {
            addCriterion("application_version_id <", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdLessThanOrEqualTo(String value) {
            addCriterion("application_version_id <=", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdLike(String value) {
            addCriterion("application_version_id like", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdNotLike(String value) {
            addCriterion("application_version_id not like", value, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdIn(List<String> values) {
            addCriterion("application_version_id in", values, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdNotIn(List<String> values) {
            addCriterion("application_version_id not in", values, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdBetween(String value1, String value2) {
            addCriterion("application_version_id between", value1, value2, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andApplicationVersionIdNotBetween(String value1, String value2) {
            addCriterion("application_version_id not between", value1, value2, "applicationVersionId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdIsNull() {
            addCriterion("cloud_server_id is null");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdIsNotNull() {
            addCriterion("cloud_server_id is not null");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdEqualTo(String value) {
            addCriterion("cloud_server_id =", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdNotEqualTo(String value) {
            addCriterion("cloud_server_id <>", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdGreaterThan(String value) {
            addCriterion("cloud_server_id >", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdGreaterThanOrEqualTo(String value) {
            addCriterion("cloud_server_id >=", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdLessThan(String value) {
            addCriterion("cloud_server_id <", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdLessThanOrEqualTo(String value) {
            addCriterion("cloud_server_id <=", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdLike(String value) {
            addCriterion("cloud_server_id like", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdNotLike(String value) {
            addCriterion("cloud_server_id not like", value, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdIn(List<String> values) {
            addCriterion("cloud_server_id in", values, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdNotIn(List<String> values) {
            addCriterion("cloud_server_id not in", values, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdBetween(String value1, String value2) {
            addCriterion("cloud_server_id between", value1, value2, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andCloudServerIdNotBetween(String value1, String value2) {
            addCriterion("cloud_server_id not between", value1, value2, "cloudServerId");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table devops_application_deployment_event_log
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}