package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class ApplicationSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.repository_id
     *
     * @mbg.generated
     */
    private String repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.application_id
     *
     * @mbg.generated
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.name_rule
     *
     * @mbg.generated
     */
    private String nameRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.created_time
     *
     * @mbg.generated
     */
    private Long createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_setting.environment_value_id
     *
     * @mbg.generated
     */
    private String environmentValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.id
     *
     * @return the value of devops_application_setting.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.id
     *
     * @param id the value for devops_application_setting.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.repository_id
     *
     * @return the value of devops_application_setting.repository_id
     *
     * @mbg.generated
     */
    public String getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.repository_id
     *
     * @param repositoryId the value for devops_application_setting.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(String repositoryId) {
        this.repositoryId = repositoryId == null ? null : repositoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.path
     *
     * @return the value of devops_application_setting.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.path
     *
     * @param path the value for devops_application_setting.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.application_id
     *
     * @return the value of devops_application_setting.application_id
     *
     * @mbg.generated
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.application_id
     *
     * @param applicationId the value for devops_application_setting.application_id
     *
     * @mbg.generated
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId == null ? null : applicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.name_rule
     *
     * @return the value of devops_application_setting.name_rule
     *
     * @mbg.generated
     */
    public String getNameRule() {
        return nameRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.name_rule
     *
     * @param nameRule the value for devops_application_setting.name_rule
     *
     * @mbg.generated
     */
    public void setNameRule(String nameRule) {
        this.nameRule = nameRule == null ? null : nameRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.created_time
     *
     * @return the value of devops_application_setting.created_time
     *
     * @mbg.generated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.created_time
     *
     * @param createdTime the value for devops_application_setting.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_setting.environment_value_id
     *
     * @return the value of devops_application_setting.environment_value_id
     *
     * @mbg.generated
     */
    public String getEnvironmentValueId() {
        return environmentValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_setting.environment_value_id
     *
     * @param environmentValueId the value for devops_application_setting.environment_value_id
     *
     * @mbg.generated
     */
    public void setEnvironmentValueId(String environmentValueId) {
        this.environmentValueId = environmentValueId == null ? null : environmentValueId.trim();
    }
}