package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class ApplicationVersion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.application_id
     *
     * @mbg.generated
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.created_time
     *
     * @mbg.generated
     */
    private Long createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.application_repository_id
     *
     * @mbg.generated
     */
    private String applicationRepositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.last_deployment_time
     *
     * @mbg.generated
     */
    private Long lastDeploymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_version.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_version
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.id
     *
     * @return the value of devops_application_version.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.id
     *
     * @param id the value for devops_application_version.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.application_id
     *
     * @return the value of devops_application_version.application_id
     *
     * @mbg.generated
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.application_id
     *
     * @param applicationId the value for devops_application_version.application_id
     *
     * @mbg.generated
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId == null ? null : applicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.name
     *
     * @return the value of devops_application_version.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.name
     *
     * @param name the value for devops_application_version.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.created_time
     *
     * @return the value of devops_application_version.created_time
     *
     * @mbg.generated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.created_time
     *
     * @param createdTime the value for devops_application_version.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.description
     *
     * @return the value of devops_application_version.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.description
     *
     * @param description the value for devops_application_version.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.application_repository_id
     *
     * @return the value of devops_application_version.application_repository_id
     *
     * @mbg.generated
     */
    public String getApplicationRepositoryId() {
        return applicationRepositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.application_repository_id
     *
     * @param applicationRepositoryId the value for devops_application_version.application_repository_id
     *
     * @mbg.generated
     */
    public void setApplicationRepositoryId(String applicationRepositoryId) {
        this.applicationRepositoryId = applicationRepositoryId == null ? null : applicationRepositoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.last_deployment_time
     *
     * @return the value of devops_application_version.last_deployment_time
     *
     * @mbg.generated
     */
    public Long getLastDeploymentTime() {
        return lastDeploymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.last_deployment_time
     *
     * @param lastDeploymentTime the value for devops_application_version.last_deployment_time
     *
     * @mbg.generated
     */
    public void setLastDeploymentTime(Long lastDeploymentTime) {
        this.lastDeploymentTime = lastDeploymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_version.location
     *
     * @return the value of devops_application_version.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_version.location
     *
     * @param location the value for devops_application_version.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}