package com.fit2cloud.devops.base.domain;

import java.io.Serializable;
import java.util.Objects;

public class ApplicationDeploymentLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.deployment_id
     *
     * @mbg.generated
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.cloud_server_id
     *
     * @mbg.generated
     */
    private String cloudServerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.progress
     *
     * @mbg.generated
     */
    private Double progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.application_version_id
     *
     * @mbg.generated
     */
    private String applicationVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_application_deployment_log.stdout
     *
     * @mbg.generated
     */
    private String stdout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_application_deployment_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.id
     *
     * @return the value of devops_application_deployment_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.id
     *
     * @param id the value for devops_application_deployment_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.deployment_id
     *
     * @return the value of devops_application_deployment_log.deployment_id
     *
     * @mbg.generated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.deployment_id
     *
     * @param deploymentId the value for devops_application_deployment_log.deployment_id
     *
     * @mbg.generated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.cloud_server_id
     *
     * @return the value of devops_application_deployment_log.cloud_server_id
     *
     * @mbg.generated
     */
    public String getCloudServerId() {
        return cloudServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.cloud_server_id
     *
     * @param cloudServerId the value for devops_application_deployment_log.cloud_server_id
     *
     * @mbg.generated
     */
    public void setCloudServerId(String cloudServerId) {
        this.cloudServerId = cloudServerId == null ? null : cloudServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.start_time
     *
     * @return the value of devops_application_deployment_log.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.start_time
     *
     * @param startTime the value for devops_application_deployment_log.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.end_time
     *
     * @return the value of devops_application_deployment_log.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.end_time
     *
     * @param endTime the value for devops_application_deployment_log.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.status
     *
     * @return the value of devops_application_deployment_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.status
     *
     * @param status the value for devops_application_deployment_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.progress
     *
     * @return the value of devops_application_deployment_log.progress
     *
     * @mbg.generated
     */
    public Double getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.progress
     *
     * @param progress the value for devops_application_deployment_log.progress
     *
     * @mbg.generated
     */
    public void setProgress(Double progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.application_version_id
     *
     * @return the value of devops_application_deployment_log.application_version_id
     *
     * @mbg.generated
     */
    public String getApplicationVersionId() {
        return applicationVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.application_version_id
     *
     * @param applicationVersionId the value for devops_application_deployment_log.application_version_id
     *
     * @mbg.generated
     */
    public void setApplicationVersionId(String applicationVersionId) {
        this.applicationVersionId = applicationVersionId == null ? null : applicationVersionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_application_deployment_log.stdout
     *
     * @return the value of devops_application_deployment_log.stdout
     *
     * @mbg.generated
     */
    public String getStdout() {
        return stdout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_application_deployment_log.stdout
     *
     * @param stdout the value for devops_application_deployment_log.stdout
     *
     * @mbg.generated
     */
    public void setStdout(String stdout) {
        this.stdout = stdout == null ? null : stdout.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ApplicationDeploymentLog that = (ApplicationDeploymentLog) o;
        return Objects.equals(id, that.id) && Objects.equals(deploymentId, that.deploymentId) && Objects.equals(cloudServerId, that.cloudServerId) && Objects.equals(startTime, that.startTime) && Objects.equals(endTime, that.endTime) && Objects.equals(status, that.status) && Objects.equals(progress, that.progress) && Objects.equals(applicationVersionId, that.applicationVersionId) && Objects.equals(stdout, that.stdout);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, deploymentId, cloudServerId, startTime, endTime, status, progress, applicationVersionId, stdout);
    }
}