package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class DevopsJenkinsJobHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.job_id
     *
     * @mbg.generated
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.order_num
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.build_time
     *
     * @mbg.generated
     */
    private Long buildTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.duration_time
     *
     * @mbg.generated
     */
    private Long durationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.is_building
     *
     * @mbg.generated
     */
    private Boolean isBuilding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.build_status
     *
     * @mbg.generated
     */
    private String buildStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.sync_time
     *
     * @mbg.generated
     */
    private Long syncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.trigger_user
     *
     * @mbg.generated
     */
    private String triggerUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.sync_status
     *
     * @mbg.generated
     */
    private String syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_job_history.actions
     *
     */
    private String actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_jenkins_job_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.id
     *
     * @return the value of devops_jenkins_job_history.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.id
     *
     * @param id the value for devops_jenkins_job_history.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.job_name
     *
     * @return the value of devops_jenkins_job_history.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.job_name
     *
     * @param jobName the value for devops_jenkins_job_history.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.job_id
     *
     * @return the value of devops_jenkins_job_history.job_id
     *
     * @mbg.generated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.job_id
     *
     * @param jobId the value for devops_jenkins_job_history.job_id
     *
     * @mbg.generated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.name
     *
     * @return the value of devops_jenkins_job_history.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.name
     *
     * @param name the value for devops_jenkins_job_history.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.order_num
     *
     * @return the value of devops_jenkins_job_history.order_num
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.order_num
     *
     * @param orderNum the value for devops_jenkins_job_history.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.url
     *
     * @return the value of devops_jenkins_job_history.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.url
     *
     * @param url the value for devops_jenkins_job_history.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.build_time
     *
     * @return the value of devops_jenkins_job_history.build_time
     *
     * @mbg.generated
     */
    public Long getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.build_time
     *
     * @param buildTime the value for devops_jenkins_job_history.build_time
     *
     * @mbg.generated
     */
    public void setBuildTime(Long buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.duration_time
     *
     * @return the value of devops_jenkins_job_history.duration_time
     *
     * @mbg.generated
     */
    public Long getDurationTime() {
        return durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.duration_time
     *
     * @param durationTime the value for devops_jenkins_job_history.duration_time
     *
     * @mbg.generated
     */
    public void setDurationTime(Long durationTime) {
        this.durationTime = durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.is_building
     *
     * @return the value of devops_jenkins_job_history.is_building
     *
     * @mbg.generated
     */
    public Boolean getIsBuilding() {
        return isBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.is_building
     *
     * @param isBuilding the value for devops_jenkins_job_history.is_building
     *
     * @mbg.generated
     */
    public void setIsBuilding(Boolean isBuilding) {
        this.isBuilding = isBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.description
     *
     * @return the value of devops_jenkins_job_history.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.description
     *
     * @param description the value for devops_jenkins_job_history.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.build_status
     *
     * @return the value of devops_jenkins_job_history.build_status
     *
     * @mbg.generated
     */
    public String getBuildStatus() {
        return buildStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.build_status
     *
     * @param buildStatus the value for devops_jenkins_job_history.build_status
     *
     * @mbg.generated
     */
    public void setBuildStatus(String buildStatus) {
        this.buildStatus = buildStatus == null ? null : buildStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.sync_time
     *
     * @return the value of devops_jenkins_job_history.sync_time
     *
     * @mbg.generated
     */
    public Long getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.sync_time
     *
     * @param syncTime the value for devops_jenkins_job_history.sync_time
     *
     * @mbg.generated
     */
    public void setSyncTime(Long syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.trigger_user
     *
     * @return the value of devops_jenkins_job_history.trigger_user
     *
     * @mbg.generated
     */
    public String getTriggerUser() {
        return triggerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.trigger_user
     *
     * @param triggerUser the value for devops_jenkins_job_history.trigger_user
     *
     * @mbg.generated
     */
    public void setTriggerUser(String triggerUser) {
        this.triggerUser = triggerUser == null ? null : triggerUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_job_history.sync_status
     *
     * @return the value of devops_jenkins_job_history.sync_status
     *
     * @mbg.generated
     */
    public String getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_job_history.sync_status
     *
     * @param syncStatus the value for devops_jenkins_job_history.sync_status
     *
     * @mbg.generated
     */
    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus == null ? null : syncStatus.trim();
    }


    public String getActions() {
        return actions;
    }

    public void setActions(String actions) {
        this.actions = actions;
    }
}