package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class DevopsJenkinsCredential implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.fingerprint
     *
     * @mbg.generated
     */
    private String fingerprint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.display_name
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_jenkins_credential.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_jenkins_credential
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.id
     *
     * @return the value of devops_jenkins_credential.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.id
     *
     * @param id the value for devops_jenkins_credential.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.full_name
     *
     * @return the value of devops_jenkins_credential.full_name
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.full_name
     *
     * @param fullName the value for devops_jenkins_credential.full_name
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.fingerprint
     *
     * @return the value of devops_jenkins_credential.fingerprint
     *
     * @mbg.generated
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.fingerprint
     *
     * @param fingerprint the value for devops_jenkins_credential.fingerprint
     *
     * @mbg.generated
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint == null ? null : fingerprint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.display_name
     *
     * @return the value of devops_jenkins_credential.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.display_name
     *
     * @param displayName the value for devops_jenkins_credential.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.description
     *
     * @return the value of devops_jenkins_credential.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.description
     *
     * @param description the value for devops_jenkins_credential.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.type_name
     *
     * @return the value of devops_jenkins_credential.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.type_name
     *
     * @param typeName the value for devops_jenkins_credential.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.username
     *
     * @return the value of devops_jenkins_credential.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.username
     *
     * @param username the value for devops_jenkins_credential.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_jenkins_credential.password
     *
     * @return the value of devops_jenkins_credential.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_jenkins_credential.password
     *
     * @param password the value for devops_jenkins_credential.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}