package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class ScriptImplementLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.script_id
     *
     * @mbg.generated
     */
    private String scriptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.created_time
     *
     * @mbg.generated
     */
    private Long createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.completed_time
     *
     * @mbg.generated
     */
    private Long completedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.cloud_server_id
     *
     * @mbg.generated
     */
    private String cloudServerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.workspace_id
     *
     * @mbg.generated
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.ansible_task_id
     *
     * @mbg.generated
     */
    private String ansibleTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.execute_path
     *
     * @mbg.generated
     */
    private String executePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.id
     *
     * @return the value of devops_script_implement_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.id
     *
     * @param id the value for devops_script_implement_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.script_id
     *
     * @return the value of devops_script_implement_log.script_id
     *
     * @mbg.generated
     */
    public String getScriptId() {
        return scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.script_id
     *
     * @param scriptId the value for devops_script_implement_log.script_id
     *
     * @mbg.generated
     */
    public void setScriptId(String scriptId) {
        this.scriptId = scriptId == null ? null : scriptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.created_time
     *
     * @return the value of devops_script_implement_log.created_time
     *
     * @mbg.generated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.created_time
     *
     * @param createdTime the value for devops_script_implement_log.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.status
     *
     * @return the value of devops_script_implement_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.status
     *
     * @param status the value for devops_script_implement_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.completed_time
     *
     * @return the value of devops_script_implement_log.completed_time
     *
     * @mbg.generated
     */
    public Long getCompletedTime() {
        return completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.completed_time
     *
     * @param completedTime the value for devops_script_implement_log.completed_time
     *
     * @mbg.generated
     */
    public void setCompletedTime(Long completedTime) {
        this.completedTime = completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.cloud_server_id
     *
     * @return the value of devops_script_implement_log.cloud_server_id
     *
     * @mbg.generated
     */
    public String getCloudServerId() {
        return cloudServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.cloud_server_id
     *
     * @param cloudServerId the value for devops_script_implement_log.cloud_server_id
     *
     * @mbg.generated
     */
    public void setCloudServerId(String cloudServerId) {
        this.cloudServerId = cloudServerId == null ? null : cloudServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.workspace_id
     *
     * @return the value of devops_script_implement_log.workspace_id
     *
     * @mbg.generated
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.workspace_id
     *
     * @param workspaceId the value for devops_script_implement_log.workspace_id
     *
     * @mbg.generated
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.ansible_task_id
     *
     * @return the value of devops_script_implement_log.ansible_task_id
     *
     * @mbg.generated
     */
    public String getAnsibleTaskId() {
        return ansibleTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.ansible_task_id
     *
     * @param ansibleTaskId the value for devops_script_implement_log.ansible_task_id
     *
     * @mbg.generated
     */
    public void setAnsibleTaskId(String ansibleTaskId) {
        this.ansibleTaskId = ansibleTaskId == null ? null : ansibleTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.execute_path
     *
     * @return the value of devops_script_implement_log.execute_path
     *
     * @mbg.generated
     */
    public String getExecutePath() {
        return executePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.execute_path
     *
     * @param executePath the value for devops_script_implement_log.execute_path
     *
     * @mbg.generated
     */
    public void setExecutePath(String executePath) {
        this.executePath = executePath == null ? null : executePath.trim();
    }
}