package com.fit2cloud.devops.base.domain;

import java.io.Serializable;

public class ScriptImplementLogWithBLOBs extends ScriptImplementLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.script_exec_content
     *
     * @mbg.generated
     */
    private String scriptExecContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_script_implement_log.stdout_content
     *
     * @mbg.generated
     */
    private String stdoutContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_script_implement_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.script_exec_content
     *
     * @return the value of devops_script_implement_log.script_exec_content
     *
     * @mbg.generated
     */
    public String getScriptExecContent() {
        return scriptExecContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.script_exec_content
     *
     * @param scriptExecContent the value for devops_script_implement_log.script_exec_content
     *
     * @mbg.generated
     */
    public void setScriptExecContent(String scriptExecContent) {
        this.scriptExecContent = scriptExecContent == null ? null : scriptExecContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_script_implement_log.stdout_content
     *
     * @return the value of devops_script_implement_log.stdout_content
     *
     * @mbg.generated
     */
    public String getStdoutContent() {
        return stdoutContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_script_implement_log.stdout_content
     *
     * @param stdoutContent the value for devops_script_implement_log.stdout_content
     *
     * @mbg.generated
     */
    public void setStdoutContent(String stdoutContent) {
        this.stdoutContent = stdoutContent == null ? null : stdoutContent.trim();
    }
}